collections:
  examples:
    output: true

defaults:
  -
    scope:
      path: "_examples"
    values:
      layout: "example"
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

sass:
  sass_dir: _sass